first_djangoapp/urls.py
from django.contrib import admin
from django.urls import path
from studentdb import views

app_name = 'studentdb'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.login, name='login'),
    path('index', views.index, name='index'),  # Empty path for the index page
    
    path('category/', views.category, name='category'),
    path('category/add/', views.add_category, name='add_category'),

    path('warehouse/', views.warehouse, name='warehouse'),
    path('warehouse/add/', views.add_warehouse, name='add_warehouse'),
    path('update_hidden_status/', views.update_hidden_status, name='update_hidden_status'),
    path('edit_warehouse/<int:warehouse_id>/', views.edit_warehouse, name='edit_warehouse'),
    path('export_to_word/', views.export_to_word, name='export_to_word'),
    path('calculate-total-quantity/', views.calculate_total_quantity, name='calculate_total_quantity'),
    
    path('products/', views.product, name='products'),
    path('products/add/', views.add_products, name='add_products'),
    path('update_hidden_status_products/', views.update_hidden_status_products, name='update_hidden_status_products'),
    path('edit_products/<int:product_id>/', views.edit_products, name='edit_products'),
    path('export_to_word_products/', views.export_to_word_products, name='export_to_word_products'),

    path('offices/', views.offices, name='offices'),
    path('add_offices/', views.add_offices, name='add_offices'),
    path('edit_office/<int:office_id>/', views.edit_office, name='edit_office'),
    path('update_hidden_status_offices/', views.update_hidden_status_offices, name='update_hidden_status_offices'),
    path('export_to_word_office/', views.export_to_word_office, name='export_to_word_office'),
    
    path('employees/', views.employees, name='employees'),
    path('employees/add/', views.add_employees, name='add_employees'),
    path('edit_employees/<int:employee_id>/', views.edit_employees, name='edit_employees'),
    path('update_hidden_status_employees/', views.update_hidden_status_employees, name='update_hidden_status_employees'),
    path('export_to_word_employees/', views.export_to_word_employees, name='export_to_word_employees'),

    path('orders/', views.orders, name='orders'),
    path('add_orders/add', views.add_orders, name='add_orders'),
    path('edit_orders/<int:order_id>/', views.edit_orders, name='edit_orders'),
    path('update_hidden_status_orders/', views.update_hidden_status_orders, name='update_hidden_status_orders'),
     path('export_to_word_orders/', views.export_to_word_orders, name='export_to_word_orders'),
    
    path('components/', views.components, name='components'),
    path('components/add/', views.add_components, name='add_components'),
    
    path('warehouse_movements/', views.warehouse_movements, name='warehouse_movements'),
    path('warehouse_movements/add', views.add_warehouse_movement, name='add_warehouse_movement'),
     path('export_warehouse_movements/', views.export_warehouse_movements, name='export_warehouse_movements'),
    
    path('products_movements/', views.products_movements, name='products_movements'),
    path('products_movements/add', views.add_products_movements, name='add_products_movements'),
]

studentdb/models.py
from django.db import models
from datetime import datetime

# Create your models here.

# Модель Склад
class Warehouse(models.Model):
    id = models.AutoField(primary_key=True)  # уникальный идентификатор склада
    address = models.CharField(max_length=255)  # адрес склада
    phone = models.CharField(max_length=20, null=True)  # телефонный номер склада
    hidden = models.BooleanField(default=False)
    def __str__(self):
        return '{0}'.format(self.address)

# Модель Офис
class Office(models.Model):
    id = models.AutoField(primary_key=True)  # уникальный идентификатор офиса
    address = models.CharField(max_length=255)  # адрес офиса
    area = models.IntegerField()  # площадь офиса в квадратных метрах
    phone = models.CharField(max_length=20, null=True)  # телефонный номер офиса
    hidden = models.BooleanField(default=False)
    def __str__(self):
        return '{0}'.format(self.address)

# Модель Сотрудник
class Employee(models.Model):
    id = models.AutoField(primary_key=True)  # уникальный идентификатор сотрудника
    name = models.CharField(max_length=50)  # имя сотрудника
    lastName = models.CharField(max_length=50)  # фамилия сотрудника
    hidden = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.name} {self.lastName}"

# Модель Категория
class Category(models.Model):
    id = models.AutoField(primary_key=True)  # уникальный идентификатор категории
    name = models.CharField(max_length=100, default='')  # название категории
    hidden = models.BooleanField(default=False)
    def __str__(self):
        return '{0}'.format(self.name)


# Модель Продукт - это рабочее место сотрудника или оборудование в офисе
class Product(models.Model):
    id = models.AutoField(primary_key=True)  # уникальный идентификатор продукта
    name = models.CharField(max_length=100)  # название продукта
    category = models.ForeignKey(Category, on_delete=models.CASCADE)  # связь с таблицей Категория
    hidden = models.BooleanField(default=False)
    def __str__(self):
        return '{0}'.format(self.name)
    
# Модель Заказ
class Order(models.Model):
    ORDER_STATUS_CHOICES = [
        ('PENDING', 'В ожидании'),
        ('PROCESSING', 'В обработке'),
        ('COMPLETED', 'Завершен'),
        ('CANCELLED', 'Отменен'),
    ]

    id = models.AutoField(primary_key=True)  # уникальный идентификатор заказа
    date = models.DateField()  # дата заказа
    status = models.CharField(max_length=10, choices=ORDER_STATUS_CHOICES)  # статус заказа
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)  # связь с таблицей Сотрудник
    product = models.ForeignKey(Product, on_delete=models.CASCADE)  # связь с таблицей Продукт
    comment = models.CharField(max_length=1000)  # количество заказанных продуктов
    IdOffice = models.ForeignKey(Office, on_delete=models.CASCADE)
    hidden = models.BooleanField(default=False)

# Модель Комплектующие
class Components(models.Model):
    id = models.AutoField(primary_key=True)  # уникальный идентификатор комплектующего
    name = models.CharField(max_length=100, default=None)  # название комплектующего
    hidden = models.BooleanField(default=False)
    def __str__(self):
        return '{0}'.format(self.name)
    
# Модель Складское перемещение
class WarehouseMovement(models.Model):
    id = models.AutoField(primary_key=True)  # уникальный идентификатор
    quantity = models.IntegerField()  # количество
    IdWarehousePlus = models.ForeignKey(Warehouse, on_delete=models.CASCADE, related_name='warehouse_plus')  # Складское перемещение плюс
    IdWarehouseMinus = models.ForeignKey(Warehouse, on_delete=models.CASCADE, related_name='warehouse_minus')  # Складское перемещение минус
    IdComponents = models.ForeignKey(Components, on_delete=models.CASCADE, null=True, default=None)  # связь с таблицей Комплектующие
    date = models.DateTimeField()  # дата
    Comment = models.CharField(max_length=100, default ='', null=True)  # название комплектующего
    hidden = models.BooleanField(default=False)
    def __str__(self):
        return '{0}'.format(self.id)

# Модель Продукция Перемещение
class ProductsMovement(models.Model):
    ProductsMovement_STATUS_CHOICES = [
        ('updated', 'обновлен'),
        ('substitution', 'замена'),
    ]

    id = models.AutoField(primary_key=True)
    datetime = models.DateTimeField(auto_now_add=True)  # Добавляем поле datetime
    quantity = models.IntegerField()
    IdComponents = models.ForeignKey(Components, on_delete=models.CASCADE)
    IdProduct = models.ForeignKey(Product, on_delete=models.CASCADE)
    IdWarehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE)
    status = models.CharField(max_length=100, choices=ProductsMovement_STATUS_CHOICES, default='updated')
    hidden = models.BooleanField(default=False)
    def __str__(self):
        return '{0}'.format(self.id)

templates/movement/add/add_products_movements.html
{% extends 'index.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'products_movements/add_products_movements.css' %}">
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<div class="form-container" role="form">
    <h2>Add Products Movement</h2>

    <form method="post" action="{% url 'add_products_movements' %}" autocomplete="off" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
            <label for="IdWarehouse">Warehouse ID:</label>
            <select id="IdWarehouse" name="IdWarehouse" required>
                {% for warehouse in warehouses %}
                <option value="{{ warehouse.id }}">{{ warehouse.address }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label for="quantity">Quantity:</label>
            <input type="number" id="quantity" name="quantity" required placeholder="Enter quantity">
        </div>

        <div class="form-group">
            <label for="IdComponents">Components ID:</label>
            <select id="IdComponents" name="IdComponents" required>
                {% for component in components %}
                <option value="{{ component.id }}">{{ component.name }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label for="IdProduct">Product ID:</label>
            <select id="IdProduct" name="IdProduct" required>
                {% for product in products %}
                <option value="{{ product.id }}">{{ product.name }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label for="status">Status:</label>
            <select id="status" name="status" required>
                <option value="updated">Updated</option>
                <option value="substitution">Substitution</option>
            </select>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Add</button>
            <a href="{% url 'products_movements' %}"><button type="button">Bake to Products Movements</button></a>
        </div>
    </form>
</div>

{% endblock %}

templates/movement/add/add_warehouse_movements.html
{% extends 'index.html' %}

<!DOCTYPE html>
<html>

{% block content %}

<head>
  <title>Add Warehouse Movement</title>

  {% load static %}
  <script src="{% static 'add_warehouse_movements/add_warehouse_movements.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'add_warehouse_movements/add_warehouse_movements.css' %}">
</head>


<body>
  <h2>Add Warehouse Movement</h2>

  <form method="post" action="{% url 'add_warehouse_movement' %}" onsubmit="return validateForm()">
    {% csrf_token %}

    <label for="warehouse_minus">Warehouse Minus:</label>
    <select name="warehouse_minus" id="warehouse_minus">
      {% for warehouse in warehouses %}
      <option value="{{ warehouse.id }}" data-quantity="{{ warehouse.total_quantity }}">{{ warehouse.address }}</option>
      {% endfor %}
    </select>

    <input type="hidden" name="id_warehouse_minus" id="id_warehouse_minus">

    <label for="component_name">Component Name:</label>
    <select name="component_name" id="component_name">
      {% for component in components %}
      <option value="{{ component.id }}" data-quantity="{{ component.total_quantity }}">{{ component.name }}</option>
      {% endfor %}
    </select>

    <label for="quantity">Quantity:</label>
    <input type="text" name="quantity" id="quantity">

    <label for="warehouse_plus">Warehouse Plus:</label>
    <select name="id_warehouse_plus" id="warehouse_plus">
      {% for warehouse in warehouses %}
      <option value="{{ warehouse.id }}">{{ warehouse.address }}</option>
      {% endfor %}
    </select>

    <label for="id_date">Date:</label>
    <input type="datetime-local" name="date" id="id_date" required readonly>

    <label for="comment">Comment:</label>
    <input type="text" name="comment" required>


    <div class="form-group">
      <button type="submit" class="btn btn-primary">Add</button>
      <a href="{% url 'warehouse_movements' %}"><button type="button">Bake to Warehouse Movements</button></a>
    </div>
  </form>

</body>
{% endblock %}

</html>